if(typeof v_sat=="undefined")var v_sat={};if(typeof v_csat=="undefined")var v_csat={};
(function(){var scripts=document.getElementsByTagName("script");for(var i=0;i<scripts.length;i++)if(scripts[i].src.indexOf("/sat")!==-1){var parts=scripts[i].src.split("?");if(parts.length>1){var params=parts[1].split("&");for(var a=0;a<params.length;a++){var item=params[a].split("=");var itemStr=String(item[0]);if(itemStr.substring(0,2)==="c_"&&!v_csat.hasOwnProperty(itemStr.substring(2,itemStr.length)))v_csat[itemStr.substring(2,item[0].length)]=item[1];else if(!v_sat.hasOwnProperty(item[0]))v_sat[item[0]]=
item[1]}}}})();
var sat=function(){var knownParameters=["sit","cat","cha","evt","cid","aid","eid","ctz","st","searchwords"];if(!Array.prototype.indexOf)Array.prototype.indexOf=function(obj,start){for(var i=start||0,j=this.length;i<j;i++)if(this[i]===obj)return i;return-1};var getPageScroll=function(){var x,y;if(typeof self.pageYOffset!="undefined"){y=self.pageYOffset;x=self.pageXOffset}else if(typeof document.documentElement!="undefined"&&typeof document.documentElement.scrollTop!="undefined"){y=document.documentElement.scrollTop;x=
document.documentElement.scrollLeft}else if(typeof document.body!="undefined"){y=document.body.scrollTop;x=document.body.scrollLeft}return[x,y]};var getViewportSize=function(){if(typeof window.innerWidth=="undefined")if(typeof document.documentElement!="undefined")return[document.documentElement.clientWidth,document.documentElement.clientHeight];else return[document.body.clientWidth,document.body.clientHeight];else return[window.innerWidth,window.innerHeight]};var getDomain=function(){var positions=
[],host=location.host,pos=-1;while((pos=host.indexOf(".",pos+1))>0)positions.push(pos);pos=positions.length>1&&positions[positions.length-2]+1||0;return host.substring(pos)};var generateUUID=function(length){var uuid_length=typeof length!="undefined"?length:10;var uuid="";var r=0;for(var x=0;x<uuid_length;x++){r=Math.floor(Math.random()*36)+48;if(r>57)r=r+39;uuid+=String.fromCharCode(r)}return uuid};var setCookie=function(name,value,days,domain){if(days){var date=new Date;date.setTime(date.getTime()+
days*24*60*60*1E3);var expires="; expires="+date.toGMTString()}if(domain)var domain="; domain="+domain;else var expires="";var val=name+"="+value+expires+domain+"; path=/";document.cookie=val};var readCookie=function(name){var nameEQ=name+"=";var ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==" ")c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length)}return null};var refreshCookie=function(name,days){var value=readCookie(name);
if(!value)value=generateUUID();setCookie(name,value,days,getDomain());return value};var paramBuilder=function(params){var vo="";if(typeof params!="undefined")for(key in params)if(params.hasOwnProperty(key))if(knownParameters.indexOf(key)!=-1)vo=vo+"&"+key+"="+encodeURIComponent(params[key]);else vo=vo+"&c_"+encodeURIComponent(key)+"="+encodeURIComponent(params[key]);return vo};function getClientTimezone(){var d=new Date;var tzoffset=-d.getTimezoneOffset()||d.getTimezoneOffset()*-1;return tzoffset}
var rid=function(){var match=location.search.match(new RegExp("[?&]rid=([^&]+)(&|$)"));var id=match&&decodeURIComponent(match[1].replace(/\+/g," "));return id?id:(new Date).getTime()}();var send=function(u){var i=new Image;var satProto="https:"==document.location.protocol?"https://":"http://";var sat_cd=satProto+"sat.sanoma.fi/sat";var sat_cu="/sat.gif?log=1";i.src=sat_cd+sat_cu+u+"&rid="+rid+"&cb="+(new Date).getTime()+"&ctz="+getClientTimezone()};var lastEventString="",eventCounter=0,sessionID=
refreshCookie("SanomaWebSession",1/48),visitorID=refreshCookie("SanomaWeb",180);gigyaID=readCookie("SA_UID");var event=function(event,params,defaults){var evtParams={evt:event,cid:"",ver:"2015.09.29.12.34.31 9311d11",events:eventCounter++,session:sessionID,id:visitorID,scroll:getPageScroll().join("x")};if(gigyaID)evtParams["gigya"]=gigyaID;if(typeof window.wlrcmd!="undefined"&&window.wlrcmd=="")evtParams["adblock"]=true;for(key in v_sat)evtParams[key]=v_sat[key];if(typeof v_csat!="undefined"&&v_csat instanceof Object)for(key in v_csat)if(v_csat.hasOwnProperty(key))evtParams[key]=
v_csat[key];if(typeof defaults!="undefined"&&defaults instanceof Object)for(key in defaults)if(defaults.hasOwnProperty(key))evtParams[key]=defaults[key];if(typeof params!="undefined")if(params instanceof Object)for(key in params){if(params.hasOwnProperty(key))evtParams[key]=params[key]}else evtParams.cid=params;evtParams.evt=event;var eventString=paramBuilder(evtParams);if(eventString!=lastEventString){send(eventString);lastEventString=eventString}};setTimeout(function(){if(typeof v_sat!="undefined"){if((typeof v_sat.eid==
"undefined"||v_sat.eid=="")&&typeof window.adapt_userGuidValue!="undefined")v_sat.eid=window.adapt_userGuidValue;if(typeof v_sat.evt=="undefined")v_sat.evt="content";var params={screen:screen.width+"x"+screen.height,viewport:getViewportSize().join("x"),referrer:document.referrer,currenturl:document.URL,hash:location.hash};event(v_sat.evt,params)}},1E3);return{rid:rid,event:event}}();
